name: gobin
arguments:
  ciOptions:
    skipDocker: true
  commands:
    - gobin
  description: Downloads, compiles, and runs (or just returns the binary path) of go applications.
  oss: true
  reportingTeam: fnd-dt
  slack: dev-tooling-notifications
modules:
  - name: github.com/getoutreach/stencil-actions
  - name: github.com/getoutreach/stencil-discovery
  - name: github.com/getoutreach/stencil-base
  - name: github.com/getoutreach/stencil-golang
    channel: rc
  - name: github.com/getoutreach/devbase
    channel: rc
  - name: github.com/getoutreach/stencil-outreach
  - name: github.com/getoutreach/stencil-circleci
