name: gobin
reportingTeam: fnd-dt
description: Downloads, compiles, and runs (or just returns the binary path) of go applications.
oss: true
slack: dev-tooling-notifications
library: true
commands:
  - gobin
circleAPIKey: ""
lintroller: platinum
tracing: honeycomb
metrics: datadog
releaseType: ""
deployTo:
  environments: []
arguments:
  circleAPIKey: ""
  commands:
    - gobin
  commitGuard: false
  dependencies:
    optional: []
    required: []
  description: Downloads, compiles, and runs (or just returns the binary path) of go applications.
  grpcClients: []
  kubernetes:
    groups: []
  lintroller: platinum
  metrics: datadog
  opslevel:
    confluenceSpaceKey: ""
    datadogDashboards:
      mainLink: ""
    designDocumentLink: ""
  oss: true
  releaseOptions:
    allowMajorVersions: null
    enablePrereleases: false
  reportingTeam: fnd-dt
  resources: {}
  service: false
  tracing: honeycomb
  tutorial: false
  vaultSecrets:
    - deploy/honeycomb_new/%(environment)s/honeycomb
    - deploy/launchdarkly/%(environment)s/launchdarkly
    - deploy/mint/%(environment)s/validation/mint-validator-payload
    - deploy/flagship-shared-secret/%(environment)s/authn-flagship-payload
modules:
  - name: github.com/getoutreach/stencil-base
  - name: github.com/getoutreach/stencil-golang
  - name: github.com/getoutreach/stencil-opslevel
  - name: github.com/getoutreach/stencil-outreach
  - name: github.com/getoutreach/stencil-circleci
  - name: github.com/getoutreach/stencil-actions
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: ""
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: ""
